### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by cmr** [jeremyletang/rust-portaudio#115]
# Why?

The MIT license requires reproducing countless copies of the same copyright
header with different names in the copyright field, for every MIT library in
use. The Apache license does not have this drawback, and has protections from
patent trolls and an explicit contribution licensing clause. However, the
Apache license is incompatible with GPLv2. This is why Rust is dual-licensed as
MIT/Apache (the "primary" license being Apache, MIT only for GPLv2 compat), and
doing so would be wise for this project. This also makes this crate suitable
for inclusion in the Rust standard distribution and other project using dual
MIT/Apache.

# How?

To do this, get explicit approval from each contributor of copyrightable work
(as not all contributions qualify for copyright) and then add the following to
your README:

```
## License

Licensed under either of
 * Apache License, Version 2.0 ([LICENSE-APACHE](LICENSE-APACHE) or http://www.apache.org/licenses/LICENSE-2.0)
 * MIT license ([LICENSE-MIT](LICENSE-MIT) or http://opensource.org/licenses/MIT)
at your option.

### Contribution

Unless you explicitly state otherwise, any contribution intentionally submitted
for inclusion in the work by you shall be dual licensed as above, without any
additional terms or conditions.
```

and in your license headers, use the following boilerplate (based on that used in Rust):

```
// Copyright (c) 2015 t developers
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT
// license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
```

And don't forget to update the `license` metadata in your `Cargo.toml`!

# Contributor checkoff

 - [x] @mitchmindtree
 - [ ] @jeremyletang
 - [x] @thenyeguy
 - [ ] @renato-zannon
 - [ ] @ebfe
 - [ ] @bvssvni
 - [ ] @kellydunn
 - [ ] @cyndis
 - [ ] @victor-shepardson
 - [ ] @hughrawlinson
 - [ ] @filmor
 - [ ] @niclashoyer
 - [x] @rryan
 - [ ] @tafia

**Comment by rryan** [comment]
If the rust-portaudio maintainers choose to do this, I approve.

**Comment by thenyeguy** [comment]
LGTM

**Comment by mitchmindtree** [comment]
I've considered this, but wasn't sure if it would be allowed as PortAudio itself is purely MIT? I'm not sure whether or not that restriction applies to downstream bindings in a different language though - will have to look into it further. Also, it's obviously up to @jeremyletang in the end :+1:

**Comment by cmr** [comment]
Yeah, for bindings it doesn't make sense, feel free to close ( I'm away from computer atm)

On January 8, 2016 7:51:05 PM EST, Mitchell Nordine <notifications@github.com> wrote:
>I've considered this, but wasn't sure if it would be allowed as
>PortAudio itself is purely MIT? I'm not sure whether or not that
>restriction applies to downstream bindings in a different language
>though - will have to look into it further. Also, it's obviously up to
>@jeremyletang in the end :+1: 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jeremyletang/rust-portaudio/issues/115#issuecomment-170171331

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mitchmindtree** [comment]
Cool, thanks anyways @cmr, the brief summary you gave was useful to me.
