### ISSUE TITLE
Change Stream type parameter

### ISSUE THREAD

**Issue by jeremyletang** [jeremyletang/rust-portaudio#25]
For now, the Stream stuck is parameterize over only one type. But maybe the input type can be different of the output type. Moreover, this type can be anything, so I think we should implement a internal trait on each possible SampleFormat, (f32, i32, u8, i8) which constraint the instantiation of the stream struct to these types. The only problem is that i'm not sure how we should handle the two others sample format with this technique (CustomFormat, NonInterleaved).

@mitchmindtree any thought ?

**Comment by mitchmindtree** [comment]
This was implemented a while ago, closing.
