### ISSUE TITLE
Update `portaudio` cargo package

### ISSUE THREAD

**Issue by mitchmindtree** [jeremyletang/rust-portaudio#48]
Hey @jeremyletang :) just wondering if you could `$ cargo publish` for me? I'm trying to publish sound_stream on crates.io, but to do this all dependencies must also be on crates.io and the latest version of portaudio that's up there is a bit behind.

Thanks!!

**Comment by thenyeguy** [comment]
This is the same issue as #44 :)

**Comment by mitchmindtree** [comment]
The latest version has just been [published to crates.io](https://crates.io/crates/portaudio).
