### ISSUE TITLE
Mention dependency on wget for download

### ISSUE THREAD

**Issue by killercup** [jeremyletang/rust-portaudio#55]
Build failed for me on OS X 10.10 without useful information (see below). Reading the `build.rs` I saw that `wget` was used and not installed. (`brew install wget` solves that.)

---

```plain
failed to run custom build command for `portaudio v0.3.1`
Process didn't exit successfully: `/Users/pascal/Projekte/tools/synth/target/release/build/portaudio-372af45747eb377c/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'no such file or directory', /Users/pascal/.cargo/registry/src/github.com-1ecc6299db9ec823/portaudio-0.3.1/build.rs:72
```

**Comment by mitchmindtree** [comment]
@killercup thanks for the issue, and sorry about the trouble! The build script is still new, so might still need some polish.

Maybe we would be better off using `curl` for the OS X builds as I'm pretty sure it is pre-installed @renato-zannon

**Comment by killercup** [comment]
Yes, curl is pre-installed.

**Comment by renato-zannon** [comment]
The interesting part is, on Linux it's the contrary - curl often isn't preinstalled, but wget is. I'll take a look at this, should be easy to specialize per-OS

**Comment by mitchmindtree** [comment]
@renato-zannon awesome! legend :+1:
