### ISSUE TITLE
Non-blocking Stream Callback assumes interleaved channels (ignoring non-interleaved SampleFormat)

### ISSUE THREAD

**Issue by mitchmindtree** [jeremyletang/rust-portaudio#69]
At the moment the StreamCallbackFn's signature is like this:

```Rust

/// User specified callback function.
pub type StreamCallbackFn<I, O> =
    Box<FnMut(&[I], &mut[O], u32, &StreamCallbackTimeInfo, Option<StreamCallbackFlags>)
            -> StreamCallbackResult>;

```

The `&[I]` and `&mut[O]` arguments mean we are always assuming the channels are interleaved.

In the case that channels are non-interleaved, they should be more like `&[&[I]]` and `&mut[&mut[O]]` where each outer slice is for each channel, and each inner slice is for the channel's samples.

We could make `StreamCallbackFn` an enum with all possible combinations of input and output interleaved and non-interleaved, however this would be messy internally and look a bit ugly to the user. Same goes for making the args themselves enums.

Another perhaps cleaner option would be to *always* have the args as a slice of slices (where interleaved channels are always just on the first slice), however I guess that still adds a little unnecessary noise in the callback function's type signature. This is probably my favourite option so far.

Will keep pondering on this, any suggestions appreciated!

**Comment by tafia** [comment]
Another idea would be to have iterators instead of arrays (or nested arrays) for both input and output.
I'm not an expert of audio processing so I really don't know how convenient it is to have arrays instead.
