### ISSUE TITLE
Change StreamCallbackFn from `Box<FnMut>` to generic `F: FnMut` (blocked on unboxed_closures feature)

### ISSUE THREAD

**Issue by mitchmindtree** [jeremyletang/rust-portaudio#70]
The reason this isn't yet implemented yet is because we need to be able to specify some default type (for the generic F parameter) for the case where a user gives `None` and doesn't require the non-blocking stream. This currently isn't possible without constructing some "dummy" type (to use as the default type) and implementing the Fn trait for it, which currently requires use of the `unboxed_closures` gated feature. Once the feature is stabilised we can make this change.

**Comment by tafia** [comment]
Why not using 2 different names for blocking / non blocking ? (It is also more transparent for the developer)

**Comment by mitchmindtree** [comment]
Yeah I'm fine with this - I guess it was originally taken as an Option to match the C portaudio API, but this isn't really necessary. Feel free to do this if you'd like (I won't have time for a little while).

**Comment by tafia** [comment]
Just opened a PR. I'm not good at namings but at least this is the idea.
It is obviously a breaking change
