### ISSUE TITLE
Smaller num dependency

### ISSUE THREAD

**Issue by bluss** [jeremyletang/rust-portaudio#96]
Just FYI, you can use just the traits in the num crate this way:

```
[depencencies]
num = { version = "*", default-features = false }
```

If you do this in this crate it will build a bit faster. The features were just added to num, and they are bignum, rational, complex, you don't need those, and may even avoid the deps they pull in (rustc_serialize and rand).

**Comment by bluss** [comment]
cc @mitchmindtree I saw this from your crates. You can do the same, when this dependency of yours is fixed.

**Comment by mitchmindtree** [comment]
Ahh thanks for the tip @bluss ! Every second taken back from compile time is a win in my book :+1:

**Comment by bluss** [comment]
Just to explain further, cargo sums all the feature flags for a package and its dependencies, so if any dependency needs all of `num` (or is marked as needing it), it will compile all of it.
